export const SUCCESS_LOAD_CHAT = 'SUCCESS_LOAD_CHAT';
export const SUCCESS_SAVE_NOTES = 'SUCCESS_SAVE_NOTES';
export const SUCCESS_LOAD_NEWS = 'SUCCESS_LOAD_NEWS';
export const SUCCESS_DELETE_NOTES = 'SUCCESS_DELETE_NOTES';
export const SUCCESS_GET_NOTES_COUNT = 'SUCCESS_GET_NOTES_COUNT';
export const SUCCESS_LOAD_FINANCE_DATA = 'SUCCESS_LOAD_FINANCE_DATA';
export const SUCCESS_LOAD_FILMS = 'SUCCESS_LOAD_FILMS';
export const FAILED_LOAD_FILM = 'FAILED_LOAD_FILM';
export const SUCCESS_LOAD_FILM = 'SUCCESS_LOAD_FILM';
export const CHANGE_NOTE_PAGE = 'CHANGE_NOTE_PAGE';
export const FAILED_SEARCH_FILM = 'FAILED_SEARCH_FILM';

export const BEGIN_AJAX_CALL = "BEGIN_AJAX_CALL";
export const AJAX_CALL_ERROR = "AJAX_CALL_ERROR";
