export const ROLE_NAMES = {
  PROGRAM: 'PROGRAM',
  REFERRAL_COORDINATOR: 'REFERRAL_COORDINATOR',
  PROVIDER: 'USER',
  GPA: 'GPA',
  USER: 'USER',
  ADMIN: 'ADMIN',
  TEAM_MEMBER: 'TEAM_MEMBER',
  NETWORK_MANAGER: 'NETWORK_MANAGER',
};
